name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set up SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
        run: |
          # Start the ssh-agent in the background
          eval "$(ssh-agent -s)"
          # Add the SSH private key
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          # Create the .ssh directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          # Add the EC2 host to the known hosts file
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
          # Sync the project files to the EC2 instance
          rsync -avz --delete-after . $EC2_USER@$EC2_HOST:/home/ubuntu/my-project
          # Connect to the EC2 instance and set up the project
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/my-project
            # Install PM2 globally
            npm install -g pm2
            # Install project dependencies
            npm install --production
            # Restart or start the Strapi application with PM2
            pm2 restart all || pm2 start npm --name "strapi" -- run develop
          EOF
